### ISSUE TITLE
Error: shotkey.c:188: error: unexpected end of file

### ISSUE THREAD

**Issue by Spryc** [phenax/shotkey#3]
**Steps to reproduce**

1.   git clone repo
2. run `make`

**Output:**
`
shotkey.c:188: error: unexpected end of file
make: *** [Makefile:18: shotkey.o] Error 1
`

**Note**
I am not very good at C, it is probably something easily fixable, btw love the idea of this project.

**Comment by phenax** [comment]
Not sure what is causing this. Could be related to line endings. Can you provide more information about your os/distro with version. Along with the outputs of `cc -v` and `make -v`?
