### ISSUE TITLE
[BUG?] Shift gets stuck sometimes

### ISSUE THREAD

**Issue by Dimfred** [phenax/shotkey#4]
Hi I have the feeling that sometimes the shift key is not released, are you experiencing the same behavior? 
Since this is a very sporadic error and shotkey isn't throwing any errors, I have really no other information. 

Btw I use Arch (if it matters).

**Comment by phenax** [comment]
I haven't experienced any issues like the one you've mentioned. Could you try running `xev` and using your shift key? Post your output here and also confirm if the key press and key release events show up correctly.

> Btw I use Arch

Nice

**Comment by Dimfred** [comment]
I tried it for some minutes now, the key gets released normally. Problem is that it happens when I use it my normal workflow, which requires a lot of `super` presses in different modes. I'll try a bit more, but not sure that I can replicate it. What I definitely know is when it gets stuck, I have to press `shift` once and that will trigger the release.

**Comment by phenax** [comment]
That is pretty weird. I'll try to reproduce it from my end as well and let you know. Also, does the shift-lock only happen for shotkey bindings or does it lock shift for all key presses?

**Comment by Dimfred** [comment]
Maybe you wait a bit until I publish my log `xinput` logs, still waiting for them to hit, but it happens very rarely. 
It does lock the shift for all keypresses.
One also has to say I am aditionally using `kmonad` so not sure whether those two somehow are blocking each other. I mean since there is no error on your side it could also be them.

**Comment by phenax** [comment]
If it is locking shift key for all keypresses then shotkey is unlikely to be the culprit here as shotkey is purely responsible for reading the key state. If xinput logs the keypress but not the keyrelease, then that would confirm this.

**Comment by yohannd1** [comment]
It might also be your window manager. With AwesomeWM, at least - which is the WM I'm currently using - I sometimes have issues with specific applications that consider shift as being kept pressed. I'm not fully sure what the reason is, but I suspect it's when I move a window using a Super+Shift keybinding.

**Comment by Dimfred** [comment]
Sry for the late response, I kinda got use to it and forgot about the issue. 

Anyhow, I ran it today and `xinput` shows the press, but not the release so it seems that shotkey is not responsible for it. 
So maybe it's kmonad or i3 will have to check. @YohananDiamond thx for the hint I will try to look into that.

Thanks for you help and have a god one.

**Comment by Dimfred** [comment]
Btw I found the "bug". It was a mechanical problem with my keyboard lol. I didn't expect this. :D
